AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'lib/templates/**/*'
    
Layout/LineLength:
  Max: 120
  
Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - shared_examples

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: false
