source 'https://rubygems.org'

gem 'bundler', '>= 1.3'
gem 'csv'
gem 'numo-narray-alt', '>= 0.9.9', '< 0.11'
gem 'rake', '>= 1.9.1'
gem 'rake-compiler', '>= 0.8.3'
gem 'rspec', '>= 2.13.0'
gem 'yard', '>= 0.8.7.2'
